### ISSUE TITLE
what happened to all of the other mods?

### ISSUE THREAD

**Issue by Arbifoxx** [TrueTamashii/TrueTamashii#1]
title

**Comment by Arbifoxx** [comment]
The mods u made

**Comment by Frogrilla** [comment]
I got rid of them as they are not updated and are generally pretty rubbish.

**Comment by Arbifoxx** [comment]
will banana cars ever come back? It was my favorite mod.

**Comment by Frogrilla** [comment]
Maybe, but I'm busy with Gorilla Hud currently.
